apiVersion: apps/v1
kind: Deployment
metadata:
  name: metadata-replica-set
spec:
  replicas: 3
  selector: 
    matchLabels:
      app: metadata-servcie
  strategy: 
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: metadata-servcie
    spec:
      containers:
      - name: metadata-service-pod
        image: shridharkalagi/metadata-service:2.0
        ports:
          - containerPort: 8080
        livenessProbe:
          httpGet: 
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5