apiVersion: v1
kind: Pod
metadata:
  name: metadata-service-pod
  labels:
        app: metadata-servcie1
spec:
  containers:
  - name: metadata-service-pod
    image: shridharkalagi/metadata-service:1.0
    ports:
      - containerPort: 8080
